version: "3"
services:
    db:
        image: "microsoft/mssql-server-linux:2017-latest"
        environment:
            SA_PASSWORD: "password"
            ACCEPT_EULA: "Y"

            mssql:
    image: 'microsoft/mssql-server-linux:2017-latest'
    ports:
        - '1433:1433'
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=password
    volumes:
        - './drive:/var/opt/mssql'