version: "3"
services:
    db:
        image: "microsoft/mssql-server-linux"
        environment:
            SA_PASSWORD: ""
            ACCEPT_EULA: "Y"

            mssql:
    image: 'mcr.microsoft.com/mssql/server'
    ports:
        - '1433:1433'
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=KsH2020
    volumes:
        - './drive:/var/opt/mssql'