version: '2'

services:
  minio:
    container_name: minio-s3-dummy
    image: docker.io/bitnami/minio:2021
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/data'

volumes:
  minio_data:
    driver: local
